export const mockServices = [ 
  { id: 1, type: 'venue', name: 'Taheer Guest Palace', location: 'Tarauni', capacity: 200, price: 7000, image: '/image1.jpg', rating: 4.5 },
  { id: 2, type: 'venue', name: 'Bristol Palace Hotel', location: 'Farm Centre', capacity: 500, price: 15000, image: '/image1.jpg', rating: 4.8 },
  { id: 3, type: 'venue', name: 'Prince Hotel', location: 'GRA', capacity: 300, price: 10000, image: '/image1.jpg', rating: 4.3 },
  { id: 4, type: 'venue', name: 'Green Palace Hotel', location: 'Nassarawa', capacity: 250, price: 8000, image: '/image1.jpg', rating: 4.2 },
  { id: 5, type: 'venue', name: 'Afficent Event Centre', location: 'Kofar Ruwa', capacity: 600, price: 20000, image: '/image1.jpg', rating: 4.9 },
  { id: 6, type: 'venue', name: 'Meena Event Centre', location: 'Miller Road', capacity: 400, price: 12000, image: '/image1.jpg', rating: 4.6 },
  { id: 7, type: 'venue', name: 'Royal Tropicana Hotel', location: 'Zaria Road', capacity: 350, price: 9000, image: '/image1.jpg', rating: 4.4 },
  { id: 8, type: 'venue', name: 'Horizon Hotels', location: 'Gidan Rumfa', capacity: 450, price: 13000, image: '/image1.jpg', rating: 4.7 },
  { id: 9, type: 'venue', name: 'Tahir Guest House', location: 'Hotoro', capacity: 200, price: 6000, image: '/image1.jpg', rating: 4.1 },
  { id: 10, type: 'caterer', name: 'Gusto Catering Services', location: 'Tarauni', capacity: 500, price: 15000, image: '/image1.jpg', rating: 4.8 },
  { id: 11, type: 'caterer', name: 'Food Haven', location: 'GRA', capacity: 300, price: 9000, image: '/image1.jpg', rating: 4.3 },
  { id: 12, type: 'caterer', name: 'Delicious Bites', location: 'Zaria Road', capacity: 400, price: 12000, image: '/image1.jpg', rating: 4.6 },
  { id: 13, type: 'caterer', name: 'Supreme Tastes', location: 'Farm Centre', capacity: 450, price: 14000, image: '/image1.jpg', rating: 4.7 },
  { id: 14, type: 'caterer', name: 'Royal Dishes', location: 'Miller Road', capacity: 350, price: 11000, image: '/image1.jpg', rating: 4.2 },
  { id: 15, type: 'caterer', name: 'Savor Kitchen', location: 'Hotoro', capacity: 250, price: 8000, image: '/image1.jpg', rating: 4.0 },
  { id: 16, type: 'caterer', name: 'Tasty Treats', location: 'Nassarawa', capacity: 300, price: 10000, image: '/image1.jpg', rating: 4.5 },
  { id: 17, type: 'caterer', name: 'Elite Foods', location: 'Kofar Ruwa', capacity: 400, price: 12000, image: '/image1.jpg', rating: 4.6 },
  { id: 18, type: 'caterer', name: 'Golden Cuisine', location: 'Gidan Rumfa', capacity: 500, price: 15000, image: '/image1.jpg', rating: 4.9 },
  { id: 19, type: 'caterer', name: 'Classic Caterers', location: 'GRA', capacity: 350, price: 11000, image: '/image1.jpg', rating: 4.3 },
  { id: 20, type: 'caterer', name: 'Fine Dining Services', location: 'Downtown', capacity: 450, price: 14000, image: '/image1.jpg', rating: 4.7 },
  { id: 21, type: 'musician', name: 'Hamisu Breaker', location: 'Kano City', capacity: 1000, price: 50000, image: '/image1.jpg', rating: 4.9 },
  { id: 22, type: 'musician', name: 'Naziru Sarkin Waka', location: 'Tarauni', capacity: 800, price: 40000, image: '/image1.jpg', rating: 4.8 },
  { id: 23, type: 'musician', name: 'Ali Jita', location: 'GRA', capacity: 700, price: 35000, image: '/image1.jpg', rating: 4.4 },
  { id: 24, type: 'musician', name: 'Ado Gwanja', location: 'Farm Centre', capacity: 600, price: 30000, image: '/image1.jpg', rating: 4.5 },
  { id: 25, type: 'musician', name: 'Umar M Shareef', location: 'Nassarawa', capacity: 900, price: 45000, image: '/image1.jpg', rating: 4.7 },
  { id: 26, type: 'musician', name: 'Sadiq Saleh', location: 'Zaria Road', capacity: 750, price: 32000, image: '/image1.jpg', rating: 4.3 },
  { id: 27, type: 'musician', name: 'Adam A Zango', location: 'Kofar Ruwa', capacity: 850, price: 38000, image: '/image1.jpg', rating: 4.6 }
];